version: "3.7"
services:
  db:
    image: mysql:latest
    volumes:
      - "db_data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_DATABASE: HW
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser1234
      MYSQL_ROOT_PASSWORD: dbuser1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
  tomcat:
    environment:
      - "JAVA_OPTS=-Dspring.profiles.active=dev -Djava.security.egd=file:///dev/urandom -Djava.awt.headless=true"
      - "CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
      # - "JAVA_HOME=/usr/lib/jvm/java-19-openjdk-amd64"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./HW:/usr/src/app
    links:
      - db
    restart: always
volumes:
    db_data: